@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicHNldWRvIjoiYWxhaW42OSIsImlhdCI6MTc0ODM1NTYzNywiZXhwIjoxNzQ4MzU2NTM3fQ.vBUin9YRB70tKwkmn56JzKA67xsMODiv4z0z0am61XM
POST http://localhost:3000/register
content-type: application/json

{
    "pseudo": "Manue",
    "email": "Manue@example.com",
    "password": "manuepass",
    "confirmPassword": "manuepass",
    "birth_date": "1960-05-04"
}

#fin
###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "alain69@example.com",
    "password": "alainpass"
}

#fin
###
POST http://localhost:3000/logout
content-type: application/json
Authorization: Bearer {{token}}
{

}

#fin
###

PATCH http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

{   
    "city": "Beauvais"
}

#fin
###

GET http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://localhost:3000/profile/claudine60
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://marineligny-server.eddi.cloud/messaging
Authorization: Bearer {{token}}
#fin
###

GET http://marineligny-server.eddi.cloud/message/9
content-type: application/json
Authorization: Bearer {{token}}
#fin
###

POST http://marineligny-server.eddi.cloud/message/9
content-type: application/json
Authorization: Bearer {{token}}

{
    "content": " ' / > "
}