@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiQWxhbkBleGFtcGxlLmNvbSIsInBzZXVkbyI6IkFsYW51ZXMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0OTY2MTg3NiwiZXhwIjoxNzQ5NzQ4Mjc2fQ.XggvEQUR5baYDTLwmtXwBa80_L-fpBLoEHceB8BmjTA

POST http://localhost:3000/register
content-type: application/json

{
    "pseudo": "Alanues",
    "email": "Alan@example.com",
    "password": "alanpass",
    "confirmPassword": "alanpass",
    "birth_date": "1960-05-04"
}

#fin
###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "marine.admin@example.com",
    "password": "marineAdmin"
}

#fin
###

PATCH http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

{   
    "city": "Beauvais"
}

#fin
###

GET http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://localhost:3000/profile/claudine60
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://marineligny-server.eddi.cloud/messaging
Authorization: Bearer {{token}}
#fin
###

GET http://marineligny-server.eddi.cloud/message/9
content-type: application/json
Authorization: Bearer {{token}}
#fin
###

POST http://marineligny-server.eddi.cloud/message/9
content-type: application/json
Authorization: Bearer {{token}}

{
    "content": " ' / > "
}

#fin
###

DELETE http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}
#fin
###
