@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicHNldWRvIjoiYWxhaW42OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTk3MzMxLCJleHAiOjE3NTc1OTgyMzF9.6-RV653zGB3lCD8Z7iEnjxSyQyCUzRCP6emAvBqViUw
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzU3NTk3MzMxLCJleHAiOjE3NjAxODkzMzF9.eD-JwD9yHs-ZweruxYCSYSEQ-HhBMabGfdVXH-Ei6yo; Max-Age=604800; Path=/; Expires=Thu, 18 Sep 2025 13:28:51 GMT; HttpOnly; Secure; SameSite=None

{
    "pseudo": "TokenTest",
    "email": "Tokentest@example.com",
    "password": "Tokenpass",
    "confirmPassword": "Tokenpass",
    "birth_date": "1955-03-18"
}

#fin
###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "alain69@example.com",
    "password": "alainpass"
}

#fin
###
POST http://localhost:3000/refresh-token
Content-Type: application/json
Cookie: refreshToken={{refreshToken}}

{}

#fin
###

PATCH http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

{   
    "city": "Beauvais"
}

#fin
###

GET http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://localhost:3000/profile/claudine60
content-type: application/json
Authorization: Bearer {{token}}

#fin
###

GET http://localhost:3000/messaging
Authorization: Bearer {{token}}
#fin
###

GET http://localhost:3000/message/9
content-type: application/json
Authorization: Bearer {{token}}
#fin
###

POST http://localhost:3000/message/9
content-type: application/json
Authorization: Bearer {{token}}

{
    "content": " ' / > "
}

#fin
###

DELETE http://localhost:3000/myprofile
content-type: application/json
Authorization: Bearer {{token}}
#fin
###

GET http://localhost:3000/events?localisation=p
content-type: application/json
Authorization: Bearer {{token}}

#fin
