@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhbGFpbjY5QGV4YW1wbGUuY29tIiwicHNldWRvIjoiYWxhaW42OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ3MzgwODUxLCJleHAiOjE3NDc0NjcyNTF9.EtnX-kgOZ8uEUxB0a9jZuZz0faUanhvzCcxbpMaI1zo

GET http://marineligny-server.eddi.cloud/events
Authorization: Bearer {{token}}
#fin
###
GET  http://marineligny-server.eddi.cloud/events/5
Authorization: Bearer {{token}}
#fin
###
POST http://marineligny-server.eddi.cloud/events/2
content-type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 4,
    "event_id": 2
}

#fin
###
POST http://marineligny-server.eddi.cloud/event/form
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Koh-Lanpad",
    "date": "10/06/2025",
    "description": "Viens montrer ta bravoure pendant une journée, avec des activités diverses sur le thème de talent_Koh, Sudoku grandeur nature, test de connaissance, rafraichissement et discussion en equipe autour d'un bon repas",
    "availability": 20,
    "picture": "https://picsum.photos/500/300",
    "city": "Marseille",
    "activities": [9, 4]
}

#fin
###
PATCH http://marineligny-server.eddi.cloud/events/7
content-type: application/json
Authorization: Bearer {{token}}

{   
    "name": "Café Rencontre et Discussions",
    "availability": 15,
    "city": "Toulouse",
    "activities": [2, 8]
}

#fin
###
DELETE http://marineligny-server.eddi.cloud/events/7
content-type: application/json
Authorization: Bearer {{token}}

#fin
###
